# "page_scrolling" is a feature that enables page-like behavior when navigating.
# The application will automatically adjust the View based on the scrolling direction.
page_scrolling = true

# "scroll_offset" denotes the scrolling speed.
# **Note**: this behavior only applies to customizable scrolling shortcuts
# defined in the [user-defined key bindings] section
scroll_offset = 3

# "url_open_command" is a terminal command used to open url in browser
url_open_command = "xdg-open"

[story_pooling]
# "story_pooling" is a feature that allows the application to fetch stories
# in background and store them in cache memory.
enable = true
# delay (in seconds) between two story API requests
delay = 2
# possible values for allows:
# - "front_page" -> "Story View - Front Page"
# - "story" -> "Story View - All Stories"
# - "ask_hn" -> "Story View - Ask HN"
# - "show_hn" -> "Story View - Show HN"
# - "job" -> "Story View - Jobs"
allows = ["front_page"]

[client]
# "client_timeout" is the application's client timeout (in seconds) when making an API request
client_timeout = 32

[client.story_limit]
# "story_limit" stores the number of maximum stories displayed in a page in each View
# fields of "story_limit"
# - "search" -> "Search View"
# - "front_page" -> "Story View - Front Page"
# - "story" -> "Story View - All Stories"
# - "ask_hn" -> "Story View - Ask HN"
# - "show_hn" -> "Story View - Show HN"
# - "job" -> "Story View - Jobs"
search = 10
front_page = 20
story = 20
ask_hn = 15
show_hn = 15
job = 15


# ---------------------------------
# user-defined theme
# ---------------------------------

[theme]
# cursive's palette color
# (more information can be found in https://docs.rs/cursive/0.16.3/cursive/theme/index.html)
background = "#f6f6ef"
shadow = "black"
view = "#f6f6ef"
primary = "#4a4a48"
secondary = "#a5a5a5"
tertiary = "white"
title_primary = "black"
title_secondary = "yellow"
highlight = "#6c6c6c"
highlight_inactive = "blue"
highlight_text = "white"

# "additional" colors defined by the application
# "link_text" is a text color for a URL
# "link_id" is a background color for `link_id` in CommentView
# "search_highlight_bg" is a background color for matched search
# "status_bar_bg" is a background color for the status bar
# "code_block_bg" is a background color for a code block
link_text = "#4fbbfd"
link_id_bg = "#ffff00"
search_highlight_bg = "#ffff00"
status_bar_bg = "#ff6600"
code_block_bg = "#c8c8c8"

# ---------------------------------
# user-defined key bindings
# ---------------------------------
# Go to the end of this section to see list of supported keys

[keymap.global_keymap]
open_help_dialog = "?"
quit = "C-q"
close_dialog = "esc"
goto_previous_view = "C-p"
goto_front_page_view = "C-f"
goto_search_view = "C-s"
goto_all_stories_view = "C-z"
goto_ask_hn_view = "C-x"
goto_show_hn_view = "C-c"
goto_jobs_view = "C-v"

[keymap.story_view_keymap]
next_story = "j"
prev_story = "k"
goto_story = "g"
next_page = "n"
prev_page = "p"
toggle_sort_by = "d"
filter_past_day = "q"
filter_past_week = "w"
filter_past_month = "e"
filter_past_year = "r"
open_article_in_browser = "o"
open_article_in_article_view = "O"
open_story_in_browser = "s"
goto_story_comment_view = "enter"

[keymap.search_view_keymap]
to_navigation_mode = "esc"
to_search_mode = "i"

[keymap.comment_view_keymap]
next_comment = "j"
prev_comment = "k"
next_top_level_comment = "n"
prev_top_level_comment = "p"
next_leq_level_comment = "l"
prev_leq_level_comment = "h"
down = 'j'
up = 'k'
page_down = 'd'
page_up = 'u'
open_comment_in_browser = "c"
open_link_in_browser = "f"
open_link_in_article_view = "F"
reload_comment_view = "r"

[keymap.article_view_keymap]
down = 'j'
up = 'k'
page_down = 'd'
page_up = 'u'
top = 't'
bottom = 'b'
open_article_in_browser = 'o'
open_link_in_browser = 'f'
open_link_in_article_view = 'F'
open_link_dialog = 'l'
link_dialog_focus_next = 'j'
link_dialog_focus_prev = 'k'
toggle_raw_markdown_mode = 'T'

# List of supported keys:
# - <char> (any single character)
# - C-<char> (ctrl-<char>)
# - M-<char> (alt-<char>)
# - enter
# - tab
# - backspace
# - esc
# - left
# - right
# - up
# - down
# - ins
# - del
# - home
# - end
# - page_up
# - page_down
# - f1
# - f2
# - f3
# - f4
# - f5
# - f6
# - f7
# - f8
# - f9
# - f10
# - f11
# - f12
